# Generated by Django 4.1.4 on 2023-02-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_remove_list_lists_list_item_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
